Release/1.63.0
ONSdigital/dp-frontend-dataset-controller pull request #452
Opened 2024-06-05 13:50 UTC by StRhys

### What

- [replace](https://github.com/ONSdigital/dp-frontend-dataset-controller/pull/450) the national statistics logo
- [update](https://github.com/ONSdigital/dp-frontend-dataset-controller/pull/451) osr logo class

### Who can review

Anyone

2024-06-05 13:58 UTC, lindenmckenzie requested changes
We're going to need to do these before release.

2024-06-05 13:58 UTC, lindenmckenzie commented on assets/templates/filterable.tmpl
> +            <h3 class="font-size--24 line-height--32 font-weight-700 tiles__title-h3 tiles__title-h3--nav"><img class="meta__image" src={{ .DatasetLandingPage.OSRLogoURL }} alt="National Statistics l
We need to update the alt text and header text here based on the conditional.

2024-06-05 13:58 UTC, lindenmckenzie commented on assets/templates/static.tmpl
> +                    <img class="meta__image" src={{ .DatasetLandingPage.OSRLogoURL }}  alt="This is an accredited National Statistic. Click for information about types of official statistics.">
This alt text will need to be updated on the conditional too.

2024-06-07 06:09 UTC, gedge approved these changes

2024-06-07 06:15 UTC, merged